on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
      - run: ./gradlew build
      - uses: Kir-Antipov/mc-publish@v2.1
        with:
          loaders: |
            fabric

          modrinth-id: 5CfaAwzS
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 573535
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.TOKEN_GITHUB }}